name: Build plugin
on:
  push:
    branches:
      - senpai
  pull_request:
    branches:
      - senpai
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install DeckyCLI
        run: |
          mkdir "$(pwd)"/cli  
          curl -L -o "$(pwd)"/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x "$(pwd)"/cli/decky

      - name: Build plugin
        run: |
          ./cli/decky plugin build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: out/Decky-SpoofDPI.zip
