name: Create Release

on:
  workflow_dispatch:

jobs:
  # run 1.build_plugin.yml first and then upload its artifact as a release asset
  build:
    uses: ./.github/workflows/1.build_plugin.yml
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true

  upload:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: plugin

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./plugin.zip
          asset_name: plugin.zip
          asset_content_type: application/zip
