name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # run 1.build_plugin.yml first and then upload its artifact as a release asset
  build:
    uses: ./.github/workflows/1.build_plugin.yml
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: true
          files: ./Decky-SpoofDPI.zip
