name: Create release on main branch tags

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/1.build_plugin.yml
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin

      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
       
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: ./Decky-SpoofDPI.zip
  